### ISSUE TITLE
 cannot load such file -- oj/introspect/introspect_ext

### ISSUE THREAD

**Issue by vinay-keshava** [meinac/oj-introspect#5]
An error occurred while loading spec_helper. - Did you mean?
                    rspec ./spec/spec_helper.rb
Failure/Error: require "oj/introspect/introspect_ext"
LoadError:
  cannot load such file -- oj/introspect/introspect_ext

Error while building the gem on debian 
No such file in https://github.com/meinac/oj-introspect/tree/master/lib/oj/introspect

**Comment by meinac** [comment]
You have to compile the project before running `rspec`, or better just run `rake` as it compiles the project and then runs the specs.

**Comment by vinay-keshava** [comment]
Fixed it thanks.
But while building the gem
it says
 oj.h: No such file or directory
seems to be related to this https://github.com/meinac/oj-introspect/issues/4
any fix for this too ?
